// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdOPXF8ON8koNHOXynYjzAul3CK5c2xY',
    appId: '1:217465557201:web:483aa0de21b419a61075f0',
    messagingSenderId: '217465557201',
    projectId: 'chat-app-9c5bb',
    authDomain: 'chat-app-9c5bb.firebaseapp.com',
    storageBucket: 'chat-app-9c5bb.appspot.com',
    measurementId: 'G-0F4FBQR5RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2RnT0pl5KwBNqPkvlB2TyhC0HcbBfo0E',
    appId: '1:217465557201:android:024fe5a702a3259e1075f0',
    messagingSenderId: '217465557201',
    projectId: 'chat-app-9c5bb',
    storageBucket: 'chat-app-9c5bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsNm16uuvZQwbG5ML6pn_zIeUmcXc-60',
    appId: '1:217465557201:ios:ed16a8ad3630a67f1075f0',
    messagingSenderId: '217465557201',
    projectId: 'chat-app-9c5bb',
    storageBucket: 'chat-app-9c5bb.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsNm16uuvZQwbG5ML6pn_zIeUmcXc-60',
    appId: '1:217465557201:ios:b14e82b4a764b5391075f0',
    messagingSenderId: '217465557201',
    projectId: 'chat-app-9c5bb',
    storageBucket: 'chat-app-9c5bb.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
